# Generated by Django 3.1.2 on 2020-11-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('Blog_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('User_ID', models.CharField(max_length=20)),
                ('Blog_Title', models.CharField(max_length=100)),
                ('Blog_Category', models.CharField(max_length=100)),
                ('Blog_Body', models.CharField(max_length=2000)),
                ('Blog_Image', models.FileField(upload_to='blogimages/')),
            ],
            options={
                'db_table': 'BlogData',
            },
        ),
    ]
